spring.application.name=ControleiApi
spring.profiles.active=local

spring.threads.virtual.enabled=true
spring.jpa.open-in-view=false

jwt.secret=625a00bc-2eb5-4f36-ab38-ab0e353069a5
jwt.expiration-hours=24

management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.health.show-details=always
management.endpoint.prometheus.enabled=true
